"""bench build: Build ID, override header, sync command, headless command, log parsing, build flow."""

import subprocess
from pathlib import Path, PurePosixPath

import pytest

from bench import build as build_mod
from bench.build import (build, config_of, headless_command, new_log_path, parse_log, repo_path)
from bench.buildid import (build_id, check_overrides, render_overrides_h, write_if_changed)
from bench.cli import main
from bench.tree import BuildTree, linked_file_parents, rsync_command
from bench.winpath import to_windows, to_wsl

DATA = Path(__file__).parent / "data"
TREE_WIN = r"C:\Users\Simon\arcfw-bench\tree"


# --- paths -----------------------------------------------------------------


def test_windows_paths():
    assert to_windows("/mnt/c/Users/Simon/arcfw-bench/tree") == TREE_WIN
    assert to_windows("/mnt/d") == "D:\\"
    assert to_wsl(TREE_WIN) == PurePosixPath("/mnt/c/Users/Simon/arcfw-bench/tree")
    with pytest.raises(ValueError):
        to_windows("/home/simon/Projects/Firmware")


# --- Build ID --------------------------------------------------------------


def git(repo, *args):
    subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)


@pytest.fixture
def repo(tmp_path):
    r = tmp_path / "fw"
    (r / "CM4").mkdir(parents=True)
    (r / "tools").mkdir()
    (r / "CM4" / "main.c").write_text("int main(void) { return 0; }\n")
    (r / "tools" / "x.py").write_text("print()\n")
    (r / ".gitignore").write_text("Debug_*/\n")
    git(r, "init", "-q")
    git(r, "-c", "user.name=t", "-c", "user.email=t@t", "add", ".")
    git(r, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "init")
    return r


def test_clean_checkout_is_the_commit(repo):
    bid = build_id(repo, {})
    assert len(bid) == 7 and "-" not in bid


def test_uncommitted_firmware_changes_are_hashed(repo):
    clean = build_id(repo, {})
    (repo / "CM4" / "main.c").write_text("int main(void) { return 1; }\n")
    one = build_id(repo, {})
    (repo / "CM4" / "main.c").write_text("int main(void) { return 2; }\n")
    two = build_id(repo, {})
    assert one.startswith(clean + "-d") and two.startswith(clean + "-d") and one != two


def test_untracked_sources_count(repo):
    clean = build_id(repo, {})
    (repo / "CM4" / "new.c").write_text("int x;\n")
    assert build_id(repo, {}).startswith(clean + "-d")


def test_host_tools_and_ignored_files_do_not_change_the_build_id(repo):
    clean = build_id(repo, {})
    (repo / "tools" / "x.py").write_text("print('changed')\n")
    (repo / "tools" / "y.py").write_text("\n")
    (repo / "CM4" / "Debug_C2").mkdir()
    (repo / "CM4" / "Debug_C2" / "main.o").write_bytes(b"\0")
    assert build_id(repo, {}) == clean


def test_overrides_are_hashed_whatever_their_order(repo):
    a = build_id(repo, {"TX_RAMP_MS": "5u", "TX_LEAD_MS": "18u"})
    b = build_id(repo, {"TX_LEAD_MS": "18u", "TX_RAMP_MS": "5u"})
    c = build_id(repo, {"TX_RAMP_MS": "6u"})
    assert a == b and "-o" in a and a != c


@pytest.mark.parametrize("overrides, problem", [
    ({"1BAD": "1"}, "not a C identifier"),
    ({"BENCH_BUILD_ID": '"x"'}, "set by bench"),
    ({"X": ""}, "non-empty"),
    ({"X": "1\n#define Y 2"}, "one non-empty line"),
])
def test_invalid_overrides_are_refused(overrides, problem):
    with pytest.raises(ValueError, match=problem):
        check_overrides(overrides)


def test_override_header():
    text = render_overrides_h("abc1234-o1", {"TX_RAMP_MS": "5u", "BENCH_RTC_START_S": "0"})
    assert text.splitlines() == [
        "/* Generated by bench (tools/bench) for one build: do not edit. */",
        '#define BENCH_BUILD_ID "abc1234-o1"',
        "#undef  BENCH_RTC_START_S",
        "#define BENCH_RTC_START_S 0",
        "#undef  TX_RAMP_MS",
        "#define TX_RAMP_MS 5u",
    ]


def test_header_is_written_only_on_a_change(tmp_path):
    h = tmp_path / "Common" / "Bench" / "bench_overrides.h"
    assert write_if_changed(h, "a\n")
    mtime = h.stat().st_mtime_ns
    assert not write_if_changed(h, "a\n")
    assert h.stat().st_mtime_ns == mtime
    assert write_if_changed(h, "b\n")


# --- sync and command ------------------------------------------------------


def test_sync_keeps_what_the_tree_owns_and_skips_host_tools():
    cmd = rsync_command(Path("/repo"), Path("/mnt/c/b/tree"))
    assert cmd[:3] == ["rsync", "-a", "--delete"]
    for excluded in ("--exclude=.git/", "--exclude=/tools/", "--exclude=/Tests/", "--exclude=Debug_*/",
                     "--exclude=/Common/Bench/bench_overrides.h"):
        assert excluded in cmd
    assert cmd[-2:] == ["/repo/", "/mnt/c/b/tree/"]


def test_sync_really_preserves_tree_outputs(tmp_path):
    repo, tree = tmp_path / "repo", tmp_path / "tree"
    (repo / "CM4").mkdir(parents=True)
    (repo / "CM4" / "main.c").write_text("x")
    (repo / "tools").mkdir()
    (repo / "tools" / "t.py").write_text("x")
    (tree / "CM4" / "Debug_C2").mkdir(parents=True)
    (tree / "CM4" / "Debug_C2" / "main.o").write_text("o")
    (tree / "Common" / "Bench").mkdir(parents=True)
    (tree / "Common" / "Bench" / "bench_overrides.h").write_text("h")
    (tree / "stale.c").write_text("gone from the repo")
    subprocess.run(rsync_command(repo, tree), check=True)
    assert (tree / "CM4" / "main.c").exists()
    assert (tree / "CM4" / "Debug_C2" / "main.o").exists()
    assert (tree / "Common" / "Bench" / "bench_overrides.h").exists()
    assert not (tree / "stale.c").exists()
    assert not (tree / "tools").exists()


PROJECT_WITH_LINKS = """<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>ArcLoRaM_Base_CM4</name>
	<linkedResources>
		<link><name>Common</name><type>2</type><locationURI>PARENT-1-PROJECT_LOC/Common</locationURI></link>
		<link><name>Utilities/stm32_seq.c</name><type>1</type><locationURI>PARENT-1-PROJECT_LOC/Utilities/sequencer/stm32_seq.c</locationURI></link>
		<link><name>Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal.c</name><type>1</type><locationURI>PARENT-1-PROJECT_LOC/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c</locationURI></link>
	</linkedResources>
</projectDescription>
"""


def test_the_parents_of_linked_files_are_found_in_the_project_files(tmp_path):
    (tmp_path / "CM4").mkdir()
    (tmp_path / "CM4" / ".project").write_text(PROJECT_WITH_LINKS)
    (tmp_path / "CM0PLUS").mkdir()
    (tmp_path / "CM0PLUS" / ".project").write_text(PROJECT_WITH_LINKS.replace("Utilities/stm32_seq.c", "Middlewares/Third_Party/x/y.c"))
    (tmp_path / "docs").mkdir()
    assert linked_file_parents(tmp_path) == [
        "CM0PLUS/Drivers", "CM0PLUS/Drivers/STM32WLxx_HAL_Driver", "CM0PLUS/Middlewares",
        "CM0PLUS/Middlewares/Third_Party", "CM0PLUS/Middlewares/Third_Party/x",
        "CM4/Drivers", "CM4/Drivers/STM32WLxx_HAL_Driver", "CM4/Utilities"]


def test_no_project_files_means_no_linked_parents(tmp_path):
    assert linked_file_parents(tmp_path / "missing") == []
    assert linked_file_parents(tmp_path) == []


def test_sync_keeps_the_folders_cubeide_makes_for_linked_files(tmp_path):
    """Issue #73: CubeIDE creates the parent folders of a project's linked files in the Build Tree.
    The repo has none of them, so a plain --delete removed them, and the next CubeIDE session
    dropped the linked HAL and Utilities sources from the project: a link error, every other build."""
    repo, tree = tmp_path / "repo", tmp_path / "tree"
    (repo / "CM4").mkdir(parents=True)
    (repo / "CM4" / ".project").write_text(PROJECT_WITH_LINKS)
    (repo / "CM4" / "main.c").write_text("x")
    for folder in ("Drivers/STM32WLxx_HAL_Driver", "Utilities", "Old"):
        (tree / "CM4" / folder).mkdir(parents=True)
    subprocess.run(rsync_command(repo, tree), check=True)
    assert (tree / "CM4" / "Drivers" / "STM32WLxx_HAL_Driver").is_dir()
    assert (tree / "CM4" / "Utilities").is_dir()
    assert not (tree / "CM4" / "Old").exists()      # what the repo dropped still goes
    assert (tree / "CM4" / "main.c").exists()


def test_headless_command_builds_both_cores_of_each_configuration():
    bt = BuildTree(Path("/mnt/c/Users/Simon/arcfw-bench"))
    cmd = headless_command("ide.exe", bt, ["Debug_C2", "Debug_C3"])
    assert cmd[cmd.index("-data") + 1] == r"C:\Users\Simon\arcfw-bench\workspace"
    assert [cmd[i + 1] for i, a in enumerate(cmd) if a == "-import"] == [
        TREE_WIN, TREE_WIN + r"\CM4", TREE_WIN + r"\CM0PLUS"]
    assert [cmd[i + 1] for i, a in enumerate(cmd) if a == "-build"] == [
        "ArcLoRaM_Base_CM4/Debug_C2", "ArcLoRaM_Base_CM0PLUS/Debug_C2",
        "ArcLoRaM_Base_CM4/Debug_C3", "ArcLoRaM_Base_CM0PLUS/Debug_C3"]


def test_classes_map_to_configurations():
    assert config_of("C3") == "Debug_C3"
    with pytest.raises(ValueError):
        config_of("C4")


# --- log -------------------------------------------------------------------


def test_diagnostic_paths_map_back_to_the_repo():
    assert repo_path("../SubGHz_Phy/App/x.c", "CM0PLUS", "Debug_C2", TREE_WIN) == "CM0PLUS/SubGHz_Phy/App/x.c"
    assert repo_path("../../Common/Log/arclog.h", "CM4", "Debug_C2", TREE_WIN) == "Common/Log/arclog.h"
    assert repo_path("C:/Users/Simon/arcfw-bench/tree/Utilities/misc/stm32_mem.c", "CM4", "Debug_C2",
                     TREE_WIN) == "Utilities/misc/stm32_mem.c"
    assert repo_path("c:\\users\\simon\\arcfw-bench\\tree\\Drivers\\x.c", "CM4", "Debug_C2",
                     TREE_WIN) == "Drivers/x.c"


def test_real_failed_log():
    log = parse_log((DATA / "headless-failed.log").read_text(), TREE_WIN)
    assert [(p.core, p.config, p.ok, p.errors) for p in log.projects] == [
        ("CM4", "Debug_C2", True, 0), ("CM0PLUS", "Debug_C2", False, 3)]
    assert [str(d) for d in log.errors] == [
        "CM0PLUS/SubGHz_Phy/App/subghz_phy_task.c:624:26: error: "
        "'undefined_symbol_for_exit_code_test' undeclared here (not in a function) [CM0PLUS Debug_C2]"]
    assert [(d.file, d.line) for d in log.warnings] == [("CM0PLUS/SubGHz_Phy/App/subghz_phy_task.c", 624)]


def test_real_ok_log_with_the_linker_warning():
    log = parse_log((DATA / "headless-ok.log").read_text(), TREE_WIN)
    assert [(p.core, p.ok) for p in log.projects] == [("CM4", True)]
    assert log.errors == []
    assert [str(d) for d in log.warnings] == [
        "ld: warning: ArcLoRaM_Base_CM4.elf has a LOAD segment with RWX permissions [CM4 Debug_C2]"]


def test_a_header_diagnostic_repeated_per_file_is_reported_once():
    text = ("**** Build of configuration Debug_C2 for project ArcLoRaM_Base_CM4 ****\n"
            "../../Common/Log/arclog.h:10:5: warning: unused [-Wunused]\n" * 3)
    assert len(parse_log(text, TREE_WIN).warnings) == 1


# --- build flow ------------------------------------------------------------


class FakeIde:
    """Writes the ELFs a headless build would, containing the Build ID read from the header."""

    def __init__(self, bt, log_text, code=0, write_elfs=True):
        self.bt, self.log_text, self.code, self.write_elfs = bt, log_text, code, write_elfs
        self.cmds = []

    def __call__(self, cmd):
        self.cmds.append(cmd)
        if self.write_elfs:
            header = self.bt.overrides_h.read_text()
            bid = header.split('BENCH_BUILD_ID "')[1].split('"')[0]
            for i, a in enumerate(cmd):
                if a in ("-build", "-cleanBuild"):
                    project, config = cmd[i + 1].split("/")
                    core = project.removeprefix("ArcLoRaM_Base_")
                    elf = self.bt.elf(core, config)
                    elf.parent.mkdir(parents=True, exist_ok=True)
                    elf.write_bytes(b"\x7fELF..." + bid.encode() + b"...")
        return self.code, self.log_text


def ok_log(configs):
    return "".join(f"**** Build of configuration {c} for project ArcLoRaM_Base_{core} ****\n"
                   f"Build Finished. 0 errors, 0 warnings. (took 1s)\n"
                   for c in configs for core in ("CM4", "CM0PLUS"))


def no_sync(repo, tree):
    tree.mkdir(parents=True, exist_ok=True)


def test_build_writes_the_header_and_checks_the_images(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    ide = FakeIde(bt, ok_log(["Debug_C2"]))
    r = build(repo, bt, ["C2", "C2"], {"TX_RAMP_MS": "5u"}, runner=ide, cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert r.ok, r.problems
    assert r.configs == ["Debug_C2"]
    assert f'#define BENCH_BUILD_ID "{r.build_id}"' in bt.overrides_h.read_text()
    assert "#define TX_RAMP_MS 5u" in bt.overrides_h.read_text()
    assert sorted(r.elfs) == [("CM0PLUS", "Debug_C2"), ("CM4", "Debug_C2")]


def test_a_stale_image_without_the_build_id_fails(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    for core in ("CM4", "CM0PLUS"):
        bt.elf(core, "Debug_C3").parent.mkdir(parents=True)
        bt.elf(core, "Debug_C3").write_bytes(b"old image")
    r = build(repo, bt, ["C3"], {}, runner=FakeIde(bt, ok_log(["Debug_C3"]), write_elfs=False),
              cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert not r.ok
    assert any("Build ID" in p and "not found" in p for p in r.problems)


def test_a_failed_build_reports_its_project(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    text = (DATA / "headless-failed.log").read_text()
    r = build(repo, bt, ["C2"], {}, runner=FakeIde(bt, text, code=1), cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert not r.ok
    assert r.problems == ["CM0PLUS Debug_C2: build failed, 3 error(s)"]


def test_a_missing_summary_is_a_failure(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    r = build(repo, bt, ["C2"], {}, runner=FakeIde(bt, "Java was started but returned exit code=13\n", code=13),
              cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert not r.ok
    assert "CM4 Debug_C2: no build summary in the CubeIDE output" in r.problems


def test_cli_build(repo, tmp_path, monkeypatch, capsys):
    bt_root = tmp_path / "bench"
    bt = BuildTree(bt_root)
    monkeypatch.setattr(build_mod, "run_process", FakeIde(bt, ok_log(["Debug_C2", "Debug_C3"])))
    monkeypatch.setattr(build_mod, "sync", no_sync)
    code = main(["--root", str(bt_root), "--repo", str(repo), "build", "--class", "C3", "--class", "C2",
                 "-D", "TX_RAMP_MS=5u"])
    out = capsys.readouterr().out
    assert code == 0, out
    assert "(Debug_C2, Debug_C3): ok, 0 error(s), 0 warning(s)" in out
    assert (bt_root / "logs").is_dir()


def test_cli_refuses_a_bad_define(repo, tmp_path, capsys):
    with pytest.raises(SystemExit):
        main(["--root", str(tmp_path), "--repo", str(repo), "build", "--class", "C2", "-D", "NOVALUE"])


def build_flags(cmd):
    return [a for a in cmd if a in ("-build", "-cleanBuild")]


def test_a_stale_image_is_rebuilt_clean_once(repo, tmp_path):
    """Objects compiled before the header existed do not depend on it (seen on the bench)."""
    bt = BuildTree(tmp_path / "bench")
    fresh = FakeIde(bt, ok_log(["Debug_C2"]))

    def ide(cmd):
        if "-cleanBuild" in cmd:
            return fresh(cmd)
        for core in ("CM4", "CM0PLUS"):  # incremental: make kept the old objects
            bt.elf(core, "Debug_C2").parent.mkdir(parents=True, exist_ok=True)
            bt.elf(core, "Debug_C2").write_bytes(b"old image, build=dev")
        fresh.cmds.append(cmd)
        return 0, ok_log(["Debug_C2"])

    r = build(repo, bt, ["C2"], {}, runner=ide, cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert r.ok, r.problems
    assert [build_flags(c) for c in fresh.cmds] == [["-build"] * 2, ["-cleanBuild"] * 2]


def test_clean_builds_clean_and_does_not_retry(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    ide = FakeIde(bt, ok_log(["Debug_C3"]), write_elfs=False)
    r = build(repo, bt, ["C3"], {}, clean=True, runner=ide, cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert not r.ok
    assert [build_flags(c) for c in ide.cmds] == [["-cleanBuild"] * 2]


# --- build logs ------------------------------------------------------------


def test_every_build_keeps_its_log_under_a_name_of_its_own(repo, tmp_path):
    """Issue #73: the log named after the Build ID alone was overwritten by the next build of the same sources."""
    bt = BuildTree(tmp_path / "bench")
    first = build(repo, bt, ["C2"], {}, runner=FakeIde(bt, ok_log(["Debug_C2"])), cubeide="ide.exe",
                  sync_tree=no_sync, windows=str)
    second = build(repo, bt, ["C2"], {}, runner=FakeIde(bt, "second build\n"), cubeide="ide.exe",
                   sync_tree=no_sync, windows=str)
    assert first.build_id == second.build_id
    assert first.log_path != second.log_path
    assert first.build_id in first.log_path.name
    assert "Build Finished" in first.log_path.read_text()
    assert "second build" in second.log_path.read_text()


def test_a_failed_build_keeps_its_full_log_and_command(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    text = (DATA / "headless-failed.log").read_text()
    r = build(repo, bt, ["C2"], {}, runner=FakeIde(bt, text, code=1), cubeide="ide.exe", sync_tree=no_sync, windows=str)
    assert not r.ok
    kept = r.log_path.read_text()
    assert text in kept
    assert kept.startswith("$ ide.exe ") and "-import" in kept.splitlines()[0]


def test_the_clean_rebuild_of_a_stale_image_goes_into_the_same_log(repo, tmp_path):
    bt = BuildTree(tmp_path / "bench")
    fresh = FakeIde(bt, ok_log(["Debug_C2"]))

    def ide(cmd):
        if "-cleanBuild" in cmd:
            code, _ = fresh(cmd)
            return code, ok_log(["Debug_C2"]) + "clean rebuild output\n"
        for core in ("CM4", "CM0PLUS"):
            bt.elf(core, "Debug_C2").parent.mkdir(parents=True, exist_ok=True)
            bt.elf(core, "Debug_C2").write_bytes(b"old image, build=dev")
        return 0, ok_log(["Debug_C2"]) + "incremental output\n"

    r = build(repo, bt, ["C2"], {}, runner=ide, cubeide="ide.exe", sync_tree=no_sync, windows=str)
    kept = r.log_path.read_text()
    assert kept.index("incremental output") < kept.index("-cleanBuild") < kept.index("clean rebuild output")
    assert len(list((bt.root / "logs").iterdir())) == 1


def test_a_log_name_is_never_reused_within_a_second(tmp_path):
    bt = BuildTree(tmp_path / "bench")
    now = build_mod.datetime(2026, 10, 5, 12, 0, 0, tzinfo=build_mod.timezone.utc)
    a = new_log_path(bt, "abc1234", now)
    a.write_text("x")
    b = new_log_path(bt, "abc1234", now)
    assert a.name == "build-20261005T120000Z-abc1234.log"
    assert b != a


def test_cli_build_prints_the_log_it_kept(repo, tmp_path, monkeypatch, capsys):
    bt_root = tmp_path / "bench"
    monkeypatch.setattr(build_mod, "run_process", FakeIde(BuildTree(bt_root), ok_log(["Debug_C2"])))
    monkeypatch.setattr(build_mod, "sync", no_sync)
    main(["--root", str(bt_root), "--repo", str(repo), "build", "--class", "C2"])
    [log] = (bt_root / "logs").iterdir()
    assert f"log {log}" in capsys.readouterr().out
