"""Build ID and the generated bench_overrides.h.

A Build ID names exactly what was built: the commit, a hash of the
uncommitted changes to the firmware sources, and a hash of the Build
Overrides:

    a1b2c3d                 clean checkout
    a1b2c3d-d5e6f7          uncommitted changes (d = dirty)
    a1b2c3d-d5e6f7-o9c0d1   and Build Overrides

Only what the Build Tree receives counts (tools/, Tests/, docs/ do not), so
editing the host tools does not change the firmware's Build ID. The firmware
logs it in BOOT on both cores; it contains no spaces.
"""

from __future__ import annotations

import hashlib
import re
import subprocess
from pathlib import Path

from bench.tree import NOT_BUILT

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
RESERVED = {"BENCH_BUILD_ID"}


def _git(repo: Path, *args: str) -> bytes:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True).stdout


def _pathspec() -> list[str]:
    return ["--", ".", *[f":(exclude){d}" for d in NOT_BUILT]]


def dirty_hash(repo: Path) -> str | None:
    """Hash of the uncommitted changes to the built sources, None when clean."""
    if not _git(repo, "status", "--porcelain", *_pathspec()).strip():
        return None
    h = hashlib.sha1()
    h.update(_git(repo, "diff", "HEAD", "--binary", *_pathspec()))
    untracked = _git(repo, "ls-files", "--others", "--exclude-standard", "-z", *_pathspec())
    for name in sorted(n for n in untracked.split(b"\0") if n):
        h.update(b"\0" + name + b"\0")
        h.update((repo / name.decode()).read_bytes())
    return h.hexdigest()[:6]


def check_overrides(overrides: dict[str, str]) -> None:
    for name, value in overrides.items():
        if not _IDENT_RE.match(name):
            raise ValueError(f"override {name!r} is not a C identifier")
        if name in RESERVED:
            raise ValueError(f"{name} is set by bench, not overridable")
        if not value or "\n" in value or "\r" in value:
            raise ValueError(f"override {name}: value must be one non-empty line")


def overrides_hash(overrides: dict[str, str]) -> str | None:
    if not overrides:
        return None
    canonical = "\n".join(f"{k}={overrides[k]}" for k in sorted(overrides))
    return hashlib.sha1(canonical.encode()).hexdigest()[:6]


def build_id(repo: Path, overrides: dict[str, str]) -> str:
    check_overrides(overrides)
    parts = [_git(repo, "rev-parse", "--short=7", "HEAD").decode().strip()]
    dirty = dirty_hash(repo)
    if dirty:
        parts.append(f"d{dirty}")
    ovr = overrides_hash(overrides)
    if ovr:
        parts.append(f"o{ovr}")
    return "-".join(parts)


def render_overrides_h(build: str, overrides: dict[str, str]) -> str:
    """The header force-included (through bench_config.h) in every C file of both cores."""
    check_overrides(overrides)
    lines = [
        "/* Generated by bench (tools/bench) for one build: do not edit. */",
        f'#define BENCH_BUILD_ID "{build}"',
    ]
    for name in sorted(overrides):
        lines += [f"#undef  {name}", f"#define {name} {overrides[name]}"]
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, text: str) -> bool:
    """Write only on a change, so an unchanged header does not force a full rebuild."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True
